# Generated by Django 6.0.4 on 2026-04-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Pessoal', 'Projeto Pessoal'), ('Disciplina', 'Projeto de Disciplina')], max_length=20)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('link_git', models.URLField()),
            ],
        ),
    ]
